/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface UpdateTodoParams {
    base: {
        status: Status;
        title: string;
        scheduledDate?: Time;
        description: string;
        priority: Priority;
    };
    groupId: bigint;
    todoId: bigint;
}
export type Time = bigint;
export interface GetGroupByNameParams {
    name: string;
}
export interface GetTodosForGroupParams {
    groupId: bigint;
}
export interface CreateGroupParams {
    kind: Kind;
    name: string;
    color: string;
}
export interface TodoBase {
    id: bigint;
    status: Status;
    title: string;
    scheduledDate?: Time;
    createdAt: Time;
    createdBy: Principal;
    description: string;
    updatedAt: Time;
    priority: Priority;
}
export interface GetTodosForGroupResp {
    ok?: Array<Todo>;
    err?: Err;
}
export type Err = {
    __kind__: "alreadyExists";
    alreadyExists: null;
} | {
    __kind__: "recordInvalid";
    recordInvalid: TodoApiErrors;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "missingMandatoryEntry";
    missingMandatoryEntry: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export interface UpdateGroupResp {
    ok?: null;
    err?: Err_1;
}
export interface UpdateTodoResp {
    ok?: null;
    err?: Err;
}
export interface GetCurrentUserRespOk {
    groups: Array<bigint>;
    user: UserBase;
}
export interface MainInterface {
    createGroup(params: CreateGroupParams): Promise<CreateGroupResp>;
    createTodo(params: CreateTodoParams): Promise<CreateTodoResp>;
    createUser(params: CreateUserParams): Promise<CreateUserResp>;
    deleteGroup(params: DeleteGroupParams): Promise<DeleteGroupResp>;
    deleteTodo(params: DeleteTodoParams): Promise<DeleteTodoResp>;
    getCurrentUser(): Promise<GetCurrentUserResp>;
    getGroupByName(params: GetGroupByNameParams): Promise<GetGroupByNameResp>;
    getTodosForGroup(params: GetTodosForGroupParams): Promise<GetTodosForGroupResp>;
    updateGroup(params: UpdateGroupParams): Promise<UpdateGroupResp>;
    updateTodo(params: UpdateTodoParams): Promise<UpdateTodoResp>;
}
export interface UpdateGroupParams {
    id: bigint;
    kind: Kind;
    name: string;
    color: string;
}
export interface GetGroupByNameResp {
    ok?: GroupBase;
    err?: Err_1;
}
export interface CreateTodoParams {
    base: {
        status: Status;
        title: string;
        scheduledDate?: Time;
        description: string;
        priority: Priority;
    };
    groupId: bigint;
}
export type Err_1 = {
    __kind__: "alreadyExists";
    alreadyExists: null;
} | {
    __kind__: "recordInvalid";
    recordInvalid: GroupApiErrors;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "missingMandatoryEntry";
    missingMandatoryEntry: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export interface GetCurrentUserResp {
    ok?: GetCurrentUserRespOk;
    err?: Err_2;
}
export interface DeleteGroupParams {
    id: bigint;
}
export interface CreateUserParams {
    name: string;
    email: string;
}
export interface CreateUserResp {
    ok?: null;
    err?: Err_2;
}
export interface UserBase {
    name: string;
    createdAt: Time;
    email: string;
}
export interface CreateGroupResp {
    ok?: GroupBase;
    err?: Err_1;
}
export interface DeleteTodoParams {
    groupId: bigint;
    todoId: bigint;
}
export interface CreateTodoResp {
    ok?: bigint;
    err?: Err;
}
export interface DeleteGroupResp {
    ok?: null;
    err?: Err_1;
}
export interface DeleteTodoResp {
    ok?: null;
    err?: Err;
}
export interface GroupBase {
    id: bigint;
    kind: Kind;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    color: string;
    updatedAt: Time;
    actorPrincipal: Principal;
}
export interface Todo {
    base: TodoBase;
}
export type Err_2 = {
    __kind__: "alreadyExists";
    alreadyExists: null;
} | {
    __kind__: "recordInvalid";
    recordInvalid: UserApiErrors;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "missingMandatoryEntry";
    missingMandatoryEntry: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export enum GroupApiErrors {
    invalidName = "invalidName",
    invalidColor = "invalidColor"
}
export enum Kind {
    collective = "collective",
    personnal = "personnal"
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Status {
    done = "done",
    todo = "todo",
    inProgress = "inProgress"
}
export enum TodoApiErrors {
    invalidTitle = "invalidTitle",
    invalidDescription = "invalidDescription"
}
export enum UserApiErrors {
    invalidEmail = "invalidEmail",
    invalidName = "invalidName"
}
export interface backendInterface extends MainInterface {
}
import type { CreateGroupParams as _CreateGroupParams, CreateGroupResp as _CreateGroupResp, CreateTodoParams as _CreateTodoParams, CreateTodoResp as _CreateTodoResp, CreateUserResp as _CreateUserResp, DeleteGroupResp as _DeleteGroupResp, DeleteTodoResp as _DeleteTodoResp, Err as _Err, Err_1 as _Err_1, Err_2 as _Err_2, GetCurrentUserResp as _GetCurrentUserResp, GetCurrentUserRespOk as _GetCurrentUserRespOk, GetGroupByNameResp as _GetGroupByNameResp, GetTodosForGroupResp as _GetTodosForGroupResp, GroupApiErrors as _GroupApiErrors, GroupBase as _GroupBase, Kind as _Kind, Priority as _Priority, Status as _Status, Time as _Time, Todo as _Todo, TodoApiErrors as _TodoApiErrors, TodoBase as _TodoBase, UpdateGroupParams as _UpdateGroupParams, UpdateGroupResp as _UpdateGroupResp, UpdateTodoParams as _UpdateTodoParams, UpdateTodoResp as _UpdateTodoResp, UserApiErrors as _UserApiErrors } from "./declarations/backend.did";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async createGroup(arg0: CreateGroupParams): Promise<CreateGroupResp> {
        const result = await this.actor.createGroup(to_candid_CreateGroupParams_n1(arg0));
        return from_candid_CreateGroupResp_n5(result);
    }
    async createTodo(arg0: CreateTodoParams): Promise<CreateTodoResp> {
        const result = await this.actor.createTodo(to_candid_CreateTodoParams_n17(arg0));
        return from_candid_CreateTodoResp_n24(result);
    }
    async createUser(arg0: CreateUserParams): Promise<CreateUserResp> {
        const result = await this.actor.createUser(arg0);
        return from_candid_CreateUserResp_n32(result);
    }
    async deleteGroup(arg0: DeleteGroupParams): Promise<DeleteGroupResp> {
        const result = await this.actor.deleteGroup(arg0);
        return from_candid_DeleteGroupResp_n40(result);
    }
    async deleteTodo(arg0: DeleteTodoParams): Promise<DeleteTodoResp> {
        const result = await this.actor.deleteTodo(arg0);
        return from_candid_DeleteTodoResp_n42(result);
    }
    async getCurrentUser(): Promise<GetCurrentUserResp> {
        const result = await this.actor.getCurrentUser();
        return from_candid_GetCurrentUserResp_n44(result);
    }
    async getGroupByName(arg0: GetGroupByNameParams): Promise<GetGroupByNameResp> {
        const result = await this.actor.getGroupByName(arg0);
        return from_candid_GetGroupByNameResp_n47(result);
    }
    async getTodosForGroup(arg0: GetTodosForGroupParams): Promise<GetTodosForGroupResp> {
        const result = await this.actor.getTodosForGroup(arg0);
        return from_candid_GetTodosForGroupResp_n48(result);
    }
    async updateGroup(arg0: UpdateGroupParams): Promise<UpdateGroupResp> {
        const result = await this.actor.updateGroup(to_candid_UpdateGroupParams_n61(arg0));
        return from_candid_UpdateGroupResp_n63(result);
    }
    async updateTodo(arg0: UpdateTodoParams): Promise<UpdateTodoResp> {
        const result = await this.actor.updateTodo(to_candid_UpdateTodoParams_n64(arg0));
        return from_candid_UpdateTodoResp_n66(result);
    }
}
function from_candid_CreateGroupResp_n5(value: _CreateGroupResp): CreateGroupResp {
    return from_candid_record_n6(value);
}
function from_candid_CreateTodoResp_n24(value: _CreateTodoResp): CreateTodoResp {
    return from_candid_record_n25(value);
}
function from_candid_CreateUserResp_n32(value: _CreateUserResp): CreateUserResp {
    return from_candid_record_n33(value);
}
function from_candid_DeleteGroupResp_n40(value: _DeleteGroupResp): DeleteGroupResp {
    return from_candid_record_n41(value);
}
function from_candid_DeleteTodoResp_n42(value: _DeleteTodoResp): DeleteTodoResp {
    return from_candid_record_n43(value);
}
function from_candid_Err_1_n13(value: _Err_1): Err_1 {
    return from_candid_variant_n14(value);
}
function from_candid_Err_2_n36(value: _Err_2): Err_2 {
    return from_candid_variant_n37(value);
}
function from_candid_Err_n28(value: _Err): Err {
    return from_candid_variant_n29(value);
}
function from_candid_GetCurrentUserResp_n44(value: _GetCurrentUserResp): GetCurrentUserResp {
    return from_candid_record_n45(value);
}
function from_candid_GetGroupByNameResp_n47(value: _GetGroupByNameResp): GetGroupByNameResp {
    return from_candid_record_n6(value);
}
function from_candid_GetTodosForGroupResp_n48(value: _GetTodosForGroupResp): GetTodosForGroupResp {
    return from_candid_record_n49(value);
}
function from_candid_GroupApiErrors_n15(value: _GroupApiErrors): GroupApiErrors {
    return from_candid_variant_n16(value);
}
function from_candid_GroupBase_n8(value: _GroupBase): GroupBase {
    return from_candid_record_n9(value);
}
function from_candid_Kind_n10(value: _Kind): Kind {
    return from_candid_variant_n11(value);
}
function from_candid_Priority_n59(value: _Priority): Priority {
    return from_candid_variant_n60(value);
}
function from_candid_Status_n56(value: _Status): Status {
    return from_candid_variant_n57(value);
}
function from_candid_TodoApiErrors_n30(value: _TodoApiErrors): TodoApiErrors {
    return from_candid_variant_n31(value);
}
function from_candid_TodoBase_n54(value: _TodoBase): TodoBase {
    return from_candid_record_n55(value);
}
function from_candid_Todo_n52(value: _Todo): Todo {
    return from_candid_record_n53(value);
}
function from_candid_UpdateGroupResp_n63(value: _UpdateGroupResp): UpdateGroupResp {
    return from_candid_record_n41(value);
}
function from_candid_UpdateTodoResp_n66(value: _UpdateTodoResp): UpdateTodoResp {
    return from_candid_record_n43(value);
}
function from_candid_UserApiErrors_n38(value: _UserApiErrors): UserApiErrors {
    return from_candid_variant_n39(value);
}
function from_candid_opt_n12(value: [] | [_Err_1]): Err_1 | null {
    return value.length === 0 ? null : from_candid_Err_1_n13(value[0]);
}
function from_candid_opt_n26(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(value: [] | [_Err]): Err | null {
    return value.length === 0 ? null : from_candid_Err_n28(value[0]);
}
function from_candid_opt_n34(value: [] | [null]): null | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(value: [] | [_Err_2]): Err_2 | null {
    return value.length === 0 ? null : from_candid_Err_2_n36(value[0]);
}
function from_candid_opt_n46(value: [] | [_GetCurrentUserRespOk]): GetCurrentUserRespOk | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(value: [] | [Array<_Todo>]): Array<Todo> | null {
    return value.length === 0 ? null : from_candid_vec_n51(value[0]);
}
function from_candid_opt_n58(value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(value: [] | [_GroupBase]): GroupBase | null {
    return value.length === 0 ? null : from_candid_GroupBase_n8(value[0]);
}
function from_candid_record_n25(value: {
    ok: [] | [bigint];
    err: [] | [_Err];
}): {
    ok?: bigint;
    err?: Err;
} {
    return {
        ok: record_opt_to_undefined(from_candid_opt_n26(value.ok)),
        err: record_opt_to_undefined(from_candid_opt_n27(value.err))
    };
}
function from_candid_record_n33(value: {
    ok: [] | [null];
    err: [] | [_Err_2];
}): {
    ok?: null;
    err?: Err_2;
} {
    return {
        ok: record_opt_to_undefined(from_candid_opt_n34(value.ok)),
        err: record_opt_to_undefined(from_candid_opt_n35(value.err))
    };
}
function from_candid_record_n41(value: {
    ok: [] | [null];
    err: [] | [_Err_1];
}): {
    ok?: null;
    err?: Err_1;
} {
    return {
        ok: record_opt_to_undefined(from_candid_opt_n34(value.ok)),
        err: record_opt_to_undefined(from_candid_opt_n12(value.err))
    };
}
function from_candid_record_n43(value: {
    ok: [] | [null];
    err: [] | [_Err];
}): {
    ok?: null;
    err?: Err;
} {
    return {
        ok: record_opt_to_undefined(from_candid_opt_n34(value.ok)),
        err: record_opt_to_undefined(from_candid_opt_n27(value.err))
    };
}
function from_candid_record_n45(value: {
    ok: [] | [_GetCurrentUserRespOk];
    err: [] | [_Err_2];
}): {
    ok?: GetCurrentUserRespOk;
    err?: Err_2;
} {
    return {
        ok: record_opt_to_undefined(from_candid_opt_n46(value.ok)),
        err: record_opt_to_undefined(from_candid_opt_n35(value.err))
    };
}
function from_candid_record_n49(value: {
    ok: [] | [Array<_Todo>];
    err: [] | [_Err];
}): {
    ok?: Array<Todo>;
    err?: Err;
} {
    return {
        ok: record_opt_to_undefined(from_candid_opt_n50(value.ok)),
        err: record_opt_to_undefined(from_candid_opt_n27(value.err))
    };
}
function from_candid_record_n53(value: {
    base: _TodoBase;
}): {
    base: TodoBase;
} {
    return {
        base: from_candid_TodoBase_n54(value.base)
    };
}
function from_candid_record_n55(value: {
    id: bigint;
    status: _Status;
    title: string;
    scheduledDate: [] | [_Time];
    createdAt: _Time;
    createdBy: Principal;
    description: string;
    updatedAt: _Time;
    priority: _Priority;
}): {
    id: bigint;
    status: Status;
    title: string;
    scheduledDate?: Time;
    createdAt: Time;
    createdBy: Principal;
    description: string;
    updatedAt: Time;
    priority: Priority;
} {
    return {
        id: value.id,
        status: from_candid_Status_n56(value.status),
        title: value.title,
        scheduledDate: record_opt_to_undefined(from_candid_opt_n58(value.scheduledDate)),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        updatedAt: value.updatedAt,
        priority: from_candid_Priority_n59(value.priority)
    };
}
function from_candid_record_n6(value: {
    ok: [] | [_GroupBase];
    err: [] | [_Err_1];
}): {
    ok?: GroupBase;
    err?: Err_1;
} {
    return {
        ok: record_opt_to_undefined(from_candid_opt_n7(value.ok)),
        err: record_opt_to_undefined(from_candid_opt_n12(value.err))
    };
}
function from_candid_record_n9(value: {
    id: bigint;
    kind: _Kind;
    name: string;
    createdAt: _Time;
    createdBy: Principal;
    color: string;
    updatedAt: _Time;
    actorPrincipal: Principal;
}): {
    id: bigint;
    kind: Kind;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    color: string;
    updatedAt: Time;
    actorPrincipal: Principal;
} {
    return {
        id: value.id,
        kind: from_candid_Kind_n10(value.kind),
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        color: value.color,
        updatedAt: value.updatedAt,
        actorPrincipal: value.actorPrincipal
    };
}
function from_candid_variant_n11(value: {
    collective: null;
} | {
    personnal: null;
}): Kind {
    return "collective" in value ? Kind.collective : "personnal" in value ? Kind.personnal : value;
}
function from_candid_variant_n14(value: {
    alreadyExists: null;
} | {
    recordInvalid: _GroupApiErrors;
} | {
    notFound: null;
} | {
    missingMandatoryEntry: null;
} | {
    unauthorized: null;
}): {
    __kind__: "alreadyExists";
    alreadyExists: null;
} | {
    __kind__: "recordInvalid";
    recordInvalid: GroupApiErrors;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "missingMandatoryEntry";
    missingMandatoryEntry: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "alreadyExists" in value ? {
        __kind__: "alreadyExists",
        alreadyExists: value.alreadyExists
    } : "recordInvalid" in value ? {
        __kind__: "recordInvalid",
        recordInvalid: from_candid_GroupApiErrors_n15(value.recordInvalid)
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "missingMandatoryEntry" in value ? {
        __kind__: "missingMandatoryEntry",
        missingMandatoryEntry: value.missingMandatoryEntry
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n16(value: {
    invalidName: null;
} | {
    invalidColor: null;
}): GroupApiErrors {
    return "invalidName" in value ? GroupApiErrors.invalidName : "invalidColor" in value ? GroupApiErrors.invalidColor : value;
}
function from_candid_variant_n29(value: {
    alreadyExists: null;
} | {
    recordInvalid: _TodoApiErrors;
} | {
    notFound: null;
} | {
    missingMandatoryEntry: null;
} | {
    unauthorized: null;
}): {
    __kind__: "alreadyExists";
    alreadyExists: null;
} | {
    __kind__: "recordInvalid";
    recordInvalid: TodoApiErrors;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "missingMandatoryEntry";
    missingMandatoryEntry: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "alreadyExists" in value ? {
        __kind__: "alreadyExists",
        alreadyExists: value.alreadyExists
    } : "recordInvalid" in value ? {
        __kind__: "recordInvalid",
        recordInvalid: from_candid_TodoApiErrors_n30(value.recordInvalid)
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "missingMandatoryEntry" in value ? {
        __kind__: "missingMandatoryEntry",
        missingMandatoryEntry: value.missingMandatoryEntry
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n31(value: {
    invalidTitle: null;
} | {
    invalidDescription: null;
}): TodoApiErrors {
    return "invalidTitle" in value ? TodoApiErrors.invalidTitle : "invalidDescription" in value ? TodoApiErrors.invalidDescription : value;
}
function from_candid_variant_n37(value: {
    alreadyExists: null;
} | {
    recordInvalid: _UserApiErrors;
} | {
    notFound: null;
} | {
    missingMandatoryEntry: null;
} | {
    unauthorized: null;
}): {
    __kind__: "alreadyExists";
    alreadyExists: null;
} | {
    __kind__: "recordInvalid";
    recordInvalid: UserApiErrors;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "missingMandatoryEntry";
    missingMandatoryEntry: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "alreadyExists" in value ? {
        __kind__: "alreadyExists",
        alreadyExists: value.alreadyExists
    } : "recordInvalid" in value ? {
        __kind__: "recordInvalid",
        recordInvalid: from_candid_UserApiErrors_n38(value.recordInvalid)
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "missingMandatoryEntry" in value ? {
        __kind__: "missingMandatoryEntry",
        missingMandatoryEntry: value.missingMandatoryEntry
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n39(value: {
    invalidEmail: null;
} | {
    invalidName: null;
}): UserApiErrors {
    return "invalidEmail" in value ? UserApiErrors.invalidEmail : "invalidName" in value ? UserApiErrors.invalidName : value;
}
function from_candid_variant_n57(value: {
    done: null;
} | {
    todo: null;
} | {
    inProgress: null;
}): Status {
    return "done" in value ? Status.done : "todo" in value ? Status.todo : "inProgress" in value ? Status.inProgress : value;
}
function from_candid_variant_n60(value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_vec_n51(value: Array<_Todo>): Array<Todo> {
    return value.map((x)=>from_candid_Todo_n52(x));
}
function to_candid_CreateGroupParams_n1(value: CreateGroupParams): _CreateGroupParams {
    return to_candid_record_n2(value);
}
function to_candid_CreateTodoParams_n17(value: CreateTodoParams): _CreateTodoParams {
    return to_candid_record_n18(value);
}
function to_candid_Kind_n3(value: Kind): _Kind {
    return to_candid_variant_n4(value);
}
function to_candid_Priority_n22(value: Priority): _Priority {
    return to_candid_variant_n23(value);
}
function to_candid_Status_n20(value: Status): _Status {
    return to_candid_variant_n21(value);
}
function to_candid_UpdateGroupParams_n61(value: UpdateGroupParams): _UpdateGroupParams {
    return to_candid_record_n62(value);
}
function to_candid_UpdateTodoParams_n64(value: UpdateTodoParams): _UpdateTodoParams {
    return to_candid_record_n65(value);
}
function to_candid_record_n18(value: {
    base: {
        status: Status;
        title: string;
        scheduledDate?: Time;
        description: string;
        priority: Priority;
    };
    groupId: bigint;
}): {
    base: {
        status: _Status;
        title: string;
        scheduledDate: [] | [_Time];
        description: string;
        priority: _Priority;
    };
    groupId: bigint;
} {
    return {
        base: to_candid_record_n19(value.base),
        groupId: value.groupId
    };
}
function to_candid_record_n19(value: {
    status: Status;
    title: string;
    scheduledDate?: Time;
    description: string;
    priority: Priority;
}): {
    status: _Status;
    title: string;
    scheduledDate: [] | [_Time];
    description: string;
    priority: _Priority;
} {
    return {
        status: to_candid_Status_n20(value.status),
        title: value.title,
        scheduledDate: value.scheduledDate ? candid_some(value.scheduledDate) : candid_none(),
        description: value.description,
        priority: to_candid_Priority_n22(value.priority)
    };
}
function to_candid_record_n2(value: {
    kind: Kind;
    name: string;
    color: string;
}): {
    kind: _Kind;
    name: string;
    color: string;
} {
    return {
        kind: to_candid_Kind_n3(value.kind),
        name: value.name,
        color: value.color
    };
}
function to_candid_record_n62(value: {
    id: bigint;
    kind: Kind;
    name: string;
    color: string;
}): {
    id: bigint;
    kind: _Kind;
    name: string;
    color: string;
} {
    return {
        id: value.id,
        kind: to_candid_Kind_n3(value.kind),
        name: value.name,
        color: value.color
    };
}
function to_candid_record_n65(value: {
    base: {
        status: Status;
        title: string;
        scheduledDate?: Time;
        description: string;
        priority: Priority;
    };
    groupId: bigint;
    todoId: bigint;
}): {
    base: {
        status: _Status;
        title: string;
        scheduledDate: [] | [_Time];
        description: string;
        priority: _Priority;
    };
    groupId: bigint;
    todoId: bigint;
} {
    return {
        base: to_candid_record_n19(value.base),
        groupId: value.groupId,
        todoId: value.todoId
    };
}
function to_candid_variant_n21(value: Status): {
    done: null;
} | {
    todo: null;
} | {
    inProgress: null;
} {
    return value == Status.done ? {
        done: null
    } : value == Status.todo ? {
        todo: null
    } : value == Status.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n23(value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(value: Kind): {
    collective: null;
} | {
    personnal: null;
} {
    return value == Kind.collective ? {
        collective: null
    } : value == Kind.personnal ? {
        personnal: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
