/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface ReqUserUpdate {
    name?: string;
    email?: string;
}
export interface ReqTodoDelete {
    todo_id: bigint;
    group_id: bigint;
}
export interface ReqGroupDelete {
    id: bigint;
}
export interface ReqTodosGetForGroup {
    group_id: bigint;
}
export interface ReqGroupCreate {
    kind: GroupKind;
    name: string;
    color: string;
}
export type Result_2 = {
    __kind__: "Ok";
    Ok: Array<ResGroupGetData>;
} | {
    __kind__: "Err";
    Err: ApiErr;
};
export interface ReqGroupAddUser {
    user_principal: Principal;
    role: GroupRole;
    group_id: bigint;
}
export type Result_6 = {
    __kind__: "Ok";
    Ok: Array<UserGetListBy>;
} | {
    __kind__: "Err";
    Err: ApiErr;
};
export interface ReqGroupsGetData {
    groups_ids: BigUint64Array;
}
export interface UserCurrentData {
    principal: Principal;
    name?: string;
    groups_ids: BigUint64Array;
    email?: string;
}
export type ApiErr = {
    __kind__: "UnexpectedErr";
    UnexpectedErr: string;
} | {
    __kind__: "InternalErr";
    InternalErr: string;
} | {
    __kind__: "DatabaseErr";
    DatabaseErr: string;
} | {
    __kind__: "Unauthorized";
    Unauthorized: string;
} | {
    __kind__: "InputErr";
    InputErr: string;
} | {
    __kind__: "ValidationErr";
    ValidationErr: Array<string>;
};
export type Result_5 = {
    __kind__: "Ok";
    Ok: UserCurrentData;
} | {
    __kind__: "Err";
    Err: ApiErr;
};
export type Result_1 = {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: ApiErr;
};
export interface ReqGroupUpdate {
    id: bigint;
    kind: GroupKind;
    name: string;
    color: string;
}
export type Result_4 = {
    __kind__: "Ok";
    Ok: Array<ReqTodoUpdate>;
} | {
    __kind__: "Err";
    Err: ApiErr;
};
export type Result = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: ApiErr;
};
export type Result_3 = {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
};
export interface ReqTodoCreate {
    status: TodoStatus;
    title: string;
    description: string;
    group_id: bigint;
    priority: TodoPriority;
    scheduled_date?: bigint;
}
export interface UserGetListBy {
    principal: Principal;
    name?: string;
    email?: string;
}
export interface ReqTodoUpdate {
    id: bigint;
    status: TodoStatus;
    title: string;
    description: string;
    group_id: bigint;
    priority: TodoPriority;
    scheduled_date?: bigint;
}
export interface ResGroupGetData {
    id: bigint;
    kind: GroupKind;
    name: string;
    color: string;
    role: GroupRole;
}
export interface ReqUsersGetListBy {
    field: UsersListByField;
    value: string;
    role: GroupRole;
}
export enum GroupKind {
    Private = "Private",
    Public = "Public"
}
export enum GroupRole {
    Guest = "Guest",
    Member = "Member",
    Admin = "Admin",
    Owner = "Owner"
}
export enum TodoPriority {
    Low = "Low",
    High = "High",
    Medium = "Medium",
    Critical = "Critical"
}
export enum TodoStatus {
    Blocked = "Blocked",
    Cancelled = "Cancelled",
    Archived = "Archived",
    InProgress = "InProgress",
    Completed = "Completed",
    Pending = "Pending"
}
export enum UsersListByField {
    Email = "Email",
    Name = "Name"
}
export interface backendInterface {
    group_add_user(arg0: ReqGroupAddUser): Promise<Result>;
    group_create(arg0: ReqGroupCreate): Promise<Result_1>;
    group_delete(arg0: ReqGroupDelete): Promise<Result>;
    group_update(arg0: ReqGroupUpdate): Promise<Result>;
    groups_get_data(arg0: ReqGroupsGetData): Promise<Result_2>;
    health_check(): Promise<Result_3>;
    todo_create(arg0: ReqTodoCreate): Promise<Result_1>;
    todo_delete(arg0: ReqTodoDelete): Promise<Result>;
    todo_update(arg0: ReqTodoUpdate): Promise<Result>;
    todos_get_for_group(arg0: ReqTodosGetForGroup): Promise<Result_4>;
    user_create(): Promise<Result>;
    user_get_current_user_data(): Promise<Result_5>;
    user_update(arg0: ReqUserUpdate): Promise<Result>;
    users_get_list_by(arg0: ReqUsersGetListBy): Promise<Result_6>;
}
import type { ApiErr as _ApiErr, GroupKind as _GroupKind, GroupRole as _GroupRole, ReqGroupAddUser as _ReqGroupAddUser, ReqGroupCreate as _ReqGroupCreate, ReqGroupUpdate as _ReqGroupUpdate, ReqTodoCreate as _ReqTodoCreate, ReqTodoUpdate as _ReqTodoUpdate, ReqUserUpdate as _ReqUserUpdate, ReqUsersGetListBy as _ReqUsersGetListBy, ResGroupGetData as _ResGroupGetData, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, TodoPriority as _TodoPriority, TodoStatus as _TodoStatus, UserCurrentData as _UserCurrentData, UserGetListBy as _UserGetListBy, UsersListByField as _UsersListByField } from "./declarations/backend.did";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async group_add_user(arg0: ReqGroupAddUser): Promise<Result> {
        const result = await this.actor.group_add_user(to_candid_ReqGroupAddUser_n1(arg0));
        return from_candid_Result_n5(result);
    }
    async group_create(arg0: ReqGroupCreate): Promise<Result_1> {
        const result = await this.actor.group_create(to_candid_ReqGroupCreate_n9(arg0));
        return from_candid_Result_1_n13(result);
    }
    async group_delete(arg0: ReqGroupDelete): Promise<Result> {
        const result = await this.actor.group_delete(arg0);
        return from_candid_Result_n5(result);
    }
    async group_update(arg0: ReqGroupUpdate): Promise<Result> {
        const result = await this.actor.group_update(to_candid_ReqGroupUpdate_n15(arg0));
        return from_candid_Result_n5(result);
    }
    async groups_get_data(arg0: ReqGroupsGetData): Promise<Result_2> {
        const result = await this.actor.groups_get_data(arg0);
        return from_candid_Result_2_n17(result);
    }
    async health_check(): Promise<Result_3> {
        const result = await this.actor.health_check();
        return from_candid_Result_3_n26(result);
    }
    async todo_create(arg0: ReqTodoCreate): Promise<Result_1> {
        const result = await this.actor.todo_create(to_candid_ReqTodoCreate_n28(arg0));
        return from_candid_Result_1_n13(result);
    }
    async todo_delete(arg0: ReqTodoDelete): Promise<Result> {
        const result = await this.actor.todo_delete(arg0);
        return from_candid_Result_n5(result);
    }
    async todo_update(arg0: ReqTodoUpdate): Promise<Result> {
        const result = await this.actor.todo_update(to_candid_ReqTodoUpdate_n34(arg0));
        return from_candid_Result_n5(result);
    }
    async todos_get_for_group(arg0: ReqTodosGetForGroup): Promise<Result_4> {
        const result = await this.actor.todos_get_for_group(arg0);
        return from_candid_Result_4_n36(result);
    }
    async user_create(): Promise<Result> {
        const result = await this.actor.user_create();
        return from_candid_Result_n5(result);
    }
    async user_get_current_user_data(): Promise<Result_5> {
        const result = await this.actor.user_get_current_user_data();
        return from_candid_Result_5_n46(result);
    }
    async user_update(arg0: ReqUserUpdate): Promise<Result> {
        const result = await this.actor.user_update(to_candid_ReqUserUpdate_n51(arg0));
        return from_candid_Result_n5(result);
    }
    async users_get_list_by(arg0: ReqUsersGetListBy): Promise<Result_6> {
        const result = await this.actor.users_get_list_by(to_candid_ReqUsersGetListBy_n53(arg0));
        return from_candid_Result_6_n57(result);
    }
}
function from_candid_ApiErr_n7(value: _ApiErr): ApiErr {
    return from_candid_variant_n8(value);
}
function from_candid_GroupKind_n22(value: _GroupKind): GroupKind {
    return from_candid_variant_n23(value);
}
function from_candid_GroupRole_n24(value: _GroupRole): GroupRole {
    return from_candid_variant_n25(value);
}
function from_candid_ReqTodoUpdate_n39(value: _ReqTodoUpdate): ReqTodoUpdate {
    return from_candid_record_n40(value);
}
function from_candid_ResGroupGetData_n20(value: _ResGroupGetData): ResGroupGetData {
    return from_candid_record_n21(value);
}
function from_candid_Result_1_n13(value: _Result_1): Result_1 {
    return from_candid_variant_n14(value);
}
function from_candid_Result_2_n17(value: _Result_2): Result_2 {
    return from_candid_variant_n18(value);
}
function from_candid_Result_3_n26(value: _Result_3): Result_3 {
    return from_candid_variant_n27(value);
}
function from_candid_Result_4_n36(value: _Result_4): Result_4 {
    return from_candid_variant_n37(value);
}
function from_candid_Result_5_n46(value: _Result_5): Result_5 {
    return from_candid_variant_n47(value);
}
function from_candid_Result_6_n57(value: _Result_6): Result_6 {
    return from_candid_variant_n58(value);
}
function from_candid_Result_n5(value: _Result): Result {
    return from_candid_variant_n6(value);
}
function from_candid_TodoPriority_n43(value: _TodoPriority): TodoPriority {
    return from_candid_variant_n44(value);
}
function from_candid_TodoStatus_n41(value: _TodoStatus): TodoStatus {
    return from_candid_variant_n42(value);
}
function from_candid_UserCurrentData_n48(value: _UserCurrentData): UserCurrentData {
    return from_candid_record_n49(value);
}
function from_candid_UserGetListBy_n60(value: _UserGetListBy): UserGetListBy {
    return from_candid_record_n61(value);
}
function from_candid_opt_n45(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(value: {
    id: bigint;
    kind: _GroupKind;
    name: string;
    color: string;
    role: _GroupRole;
}): {
    id: bigint;
    kind: GroupKind;
    name: string;
    color: string;
    role: GroupRole;
} {
    return {
        id: value.id,
        kind: from_candid_GroupKind_n22(value.kind),
        name: value.name,
        color: value.color,
        role: from_candid_GroupRole_n24(value.role)
    };
}
function from_candid_record_n40(value: {
    id: bigint;
    status: _TodoStatus;
    title: string;
    description: string;
    group_id: bigint;
    priority: _TodoPriority;
    scheduled_date: [] | [bigint];
}): {
    id: bigint;
    status: TodoStatus;
    title: string;
    description: string;
    group_id: bigint;
    priority: TodoPriority;
    scheduled_date?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TodoStatus_n41(value.status),
        title: value.title,
        description: value.description,
        group_id: value.group_id,
        priority: from_candid_TodoPriority_n43(value.priority),
        scheduled_date: record_opt_to_undefined(from_candid_opt_n45(value.scheduled_date))
    };
}
function from_candid_record_n49(value: {
    principal: Principal;
    name: [] | [string];
    groups_ids: BigUint64Array;
    email: [] | [string];
}): {
    principal: Principal;
    name?: string;
    groups_ids: BigUint64Array;
    email?: string;
} {
    return {
        principal: value.principal,
        name: record_opt_to_undefined(from_candid_opt_n50(value.name)),
        groups_ids: value.groups_ids,
        email: record_opt_to_undefined(from_candid_opt_n50(value.email))
    };
}
function from_candid_record_n61(value: {
    principal: Principal;
    name: [] | [string];
    email: [] | [string];
}): {
    principal: Principal;
    name?: string;
    email?: string;
} {
    return {
        principal: value.principal,
        name: record_opt_to_undefined(from_candid_opt_n50(value.name)),
        email: record_opt_to_undefined(from_candid_opt_n50(value.email))
    };
}
function from_candid_variant_n14(value: {
    Ok: bigint;
} | {
    Err: _ApiErr;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: ApiErr;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_ApiErr_n7(value.Err)
    } : value;
}
function from_candid_variant_n18(value: {
    Ok: Array<_ResGroupGetData>;
} | {
    Err: _ApiErr;
}): {
    __kind__: "Ok";
    Ok: Array<ResGroupGetData>;
} | {
    __kind__: "Err";
    Err: ApiErr;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n19(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_ApiErr_n7(value.Err)
    } : value;
}
function from_candid_variant_n23(value: {
    Private: null;
} | {
    Public: null;
}): GroupKind {
    return "Private" in value ? GroupKind.Private : "Public" in value ? GroupKind.Public : value;
}
function from_candid_variant_n25(value: {
    Guest: null;
} | {
    Member: null;
} | {
    Admin: null;
} | {
    Owner: null;
}): GroupRole {
    return "Guest" in value ? GroupRole.Guest : "Member" in value ? GroupRole.Member : "Admin" in value ? GroupRole.Admin : "Owner" in value ? GroupRole.Owner : value;
}
function from_candid_variant_n27(value: {
    Ok: string;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n37(value: {
    Ok: Array<_ReqTodoUpdate>;
} | {
    Err: _ApiErr;
}): {
    __kind__: "Ok";
    Ok: Array<ReqTodoUpdate>;
} | {
    __kind__: "Err";
    Err: ApiErr;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n38(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_ApiErr_n7(value.Err)
    } : value;
}
function from_candid_variant_n42(value: {
    Blocked: null;
} | {
    Cancelled: null;
} | {
    Archived: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): TodoStatus {
    return "Blocked" in value ? TodoStatus.Blocked : "Cancelled" in value ? TodoStatus.Cancelled : "Archived" in value ? TodoStatus.Archived : "InProgress" in value ? TodoStatus.InProgress : "Completed" in value ? TodoStatus.Completed : "Pending" in value ? TodoStatus.Pending : value;
}
function from_candid_variant_n44(value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
}): TodoPriority {
    return "Low" in value ? TodoPriority.Low : "High" in value ? TodoPriority.High : "Medium" in value ? TodoPriority.Medium : "Critical" in value ? TodoPriority.Critical : value;
}
function from_candid_variant_n47(value: {
    Ok: _UserCurrentData;
} | {
    Err: _ApiErr;
}): {
    __kind__: "Ok";
    Ok: UserCurrentData;
} | {
    __kind__: "Err";
    Err: ApiErr;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_UserCurrentData_n48(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_ApiErr_n7(value.Err)
    } : value;
}
function from_candid_variant_n58(value: {
    Ok: Array<_UserGetListBy>;
} | {
    Err: _ApiErr;
}): {
    __kind__: "Ok";
    Ok: Array<UserGetListBy>;
} | {
    __kind__: "Err";
    Err: ApiErr;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n59(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_ApiErr_n7(value.Err)
    } : value;
}
function from_candid_variant_n6(value: {
    Ok: null;
} | {
    Err: _ApiErr;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: ApiErr;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_ApiErr_n7(value.Err)
    } : value;
}
function from_candid_variant_n8(value: {
    UnexpectedErr: string;
} | {
    InternalErr: string;
} | {
    DatabaseErr: string;
} | {
    Unauthorized: string;
} | {
    InputErr: string;
} | {
    ValidationErr: Array<string>;
}): {
    __kind__: "UnexpectedErr";
    UnexpectedErr: string;
} | {
    __kind__: "InternalErr";
    InternalErr: string;
} | {
    __kind__: "DatabaseErr";
    DatabaseErr: string;
} | {
    __kind__: "Unauthorized";
    Unauthorized: string;
} | {
    __kind__: "InputErr";
    InputErr: string;
} | {
    __kind__: "ValidationErr";
    ValidationErr: Array<string>;
} {
    return "UnexpectedErr" in value ? {
        __kind__: "UnexpectedErr",
        UnexpectedErr: value.UnexpectedErr
    } : "InternalErr" in value ? {
        __kind__: "InternalErr",
        InternalErr: value.InternalErr
    } : "DatabaseErr" in value ? {
        __kind__: "DatabaseErr",
        DatabaseErr: value.DatabaseErr
    } : "Unauthorized" in value ? {
        __kind__: "Unauthorized",
        Unauthorized: value.Unauthorized
    } : "InputErr" in value ? {
        __kind__: "InputErr",
        InputErr: value.InputErr
    } : "ValidationErr" in value ? {
        __kind__: "ValidationErr",
        ValidationErr: value.ValidationErr
    } : value;
}
function from_candid_vec_n19(value: Array<_ResGroupGetData>): Array<ResGroupGetData> {
    return value.map((x)=>from_candid_ResGroupGetData_n20(x));
}
function from_candid_vec_n38(value: Array<_ReqTodoUpdate>): Array<ReqTodoUpdate> {
    return value.map((x)=>from_candid_ReqTodoUpdate_n39(x));
}
function from_candid_vec_n59(value: Array<_UserGetListBy>): Array<UserGetListBy> {
    return value.map((x)=>from_candid_UserGetListBy_n60(x));
}
function to_candid_GroupKind_n11(value: GroupKind): _GroupKind {
    return to_candid_variant_n12(value);
}
function to_candid_GroupRole_n3(value: GroupRole): _GroupRole {
    return to_candid_variant_n4(value);
}
function to_candid_ReqGroupAddUser_n1(value: ReqGroupAddUser): _ReqGroupAddUser {
    return to_candid_record_n2(value);
}
function to_candid_ReqGroupCreate_n9(value: ReqGroupCreate): _ReqGroupCreate {
    return to_candid_record_n10(value);
}
function to_candid_ReqGroupUpdate_n15(value: ReqGroupUpdate): _ReqGroupUpdate {
    return to_candid_record_n16(value);
}
function to_candid_ReqTodoCreate_n28(value: ReqTodoCreate): _ReqTodoCreate {
    return to_candid_record_n29(value);
}
function to_candid_ReqTodoUpdate_n34(value: ReqTodoUpdate): _ReqTodoUpdate {
    return to_candid_record_n35(value);
}
function to_candid_ReqUserUpdate_n51(value: ReqUserUpdate): _ReqUserUpdate {
    return to_candid_record_n52(value);
}
function to_candid_ReqUsersGetListBy_n53(value: ReqUsersGetListBy): _ReqUsersGetListBy {
    return to_candid_record_n54(value);
}
function to_candid_TodoPriority_n32(value: TodoPriority): _TodoPriority {
    return to_candid_variant_n33(value);
}
function to_candid_TodoStatus_n30(value: TodoStatus): _TodoStatus {
    return to_candid_variant_n31(value);
}
function to_candid_UsersListByField_n55(value: UsersListByField): _UsersListByField {
    return to_candid_variant_n56(value);
}
function to_candid_record_n10(value: {
    kind: GroupKind;
    name: string;
    color: string;
}): {
    kind: _GroupKind;
    name: string;
    color: string;
} {
    return {
        kind: to_candid_GroupKind_n11(value.kind),
        name: value.name,
        color: value.color
    };
}
function to_candid_record_n16(value: {
    id: bigint;
    kind: GroupKind;
    name: string;
    color: string;
}): {
    id: bigint;
    kind: _GroupKind;
    name: string;
    color: string;
} {
    return {
        id: value.id,
        kind: to_candid_GroupKind_n11(value.kind),
        name: value.name,
        color: value.color
    };
}
function to_candid_record_n2(value: {
    user_principal: Principal;
    role: GroupRole;
    group_id: bigint;
}): {
    user_principal: Principal;
    role: _GroupRole;
    group_id: bigint;
} {
    return {
        user_principal: value.user_principal,
        role: to_candid_GroupRole_n3(value.role),
        group_id: value.group_id
    };
}
function to_candid_record_n29(value: {
    status: TodoStatus;
    title: string;
    description: string;
    group_id: bigint;
    priority: TodoPriority;
    scheduled_date?: bigint;
}): {
    status: _TodoStatus;
    title: string;
    description: string;
    group_id: bigint;
    priority: _TodoPriority;
    scheduled_date: [] | [bigint];
} {
    return {
        status: to_candid_TodoStatus_n30(value.status),
        title: value.title,
        description: value.description,
        group_id: value.group_id,
        priority: to_candid_TodoPriority_n32(value.priority),
        scheduled_date: value.scheduled_date ? candid_some(value.scheduled_date) : candid_none()
    };
}
function to_candid_record_n35(value: {
    id: bigint;
    status: TodoStatus;
    title: string;
    description: string;
    group_id: bigint;
    priority: TodoPriority;
    scheduled_date?: bigint;
}): {
    id: bigint;
    status: _TodoStatus;
    title: string;
    description: string;
    group_id: bigint;
    priority: _TodoPriority;
    scheduled_date: [] | [bigint];
} {
    return {
        id: value.id,
        status: to_candid_TodoStatus_n30(value.status),
        title: value.title,
        description: value.description,
        group_id: value.group_id,
        priority: to_candid_TodoPriority_n32(value.priority),
        scheduled_date: value.scheduled_date ? candid_some(value.scheduled_date) : candid_none()
    };
}
function to_candid_record_n52(value: {
    name?: string;
    email?: string;
}): {
    name: [] | [string];
    email: [] | [string];
} {
    return {
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n54(value: {
    field: UsersListByField;
    value: string;
    role: GroupRole;
}): {
    field: _UsersListByField;
    value: string;
    role: _GroupRole;
} {
    return {
        field: to_candid_UsersListByField_n55(value.field),
        value: value.value,
        role: to_candid_GroupRole_n3(value.role)
    };
}
function to_candid_variant_n12(value: GroupKind): {
    Private: null;
} | {
    Public: null;
} {
    return value == GroupKind.Private ? {
        Private: null
    } : value == GroupKind.Public ? {
        Public: null
    } : value;
}
function to_candid_variant_n31(value: TodoStatus): {
    Blocked: null;
} | {
    Cancelled: null;
} | {
    Archived: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == TodoStatus.Blocked ? {
        Blocked: null
    } : value == TodoStatus.Cancelled ? {
        Cancelled: null
    } : value == TodoStatus.Archived ? {
        Archived: null
    } : value == TodoStatus.InProgress ? {
        InProgress: null
    } : value == TodoStatus.Completed ? {
        Completed: null
    } : value == TodoStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n33(value: TodoPriority): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
} {
    return value == TodoPriority.Low ? {
        Low: null
    } : value == TodoPriority.High ? {
        High: null
    } : value == TodoPriority.Medium ? {
        Medium: null
    } : value == TodoPriority.Critical ? {
        Critical: null
    } : value;
}
function to_candid_variant_n4(value: GroupRole): {
    Guest: null;
} | {
    Member: null;
} | {
    Admin: null;
} | {
    Owner: null;
} {
    return value == GroupRole.Guest ? {
        Guest: null
    } : value == GroupRole.Member ? {
        Member: null
    } : value == GroupRole.Admin ? {
        Admin: null
    } : value == GroupRole.Owner ? {
        Owner: null
    } : value;
}
function to_candid_variant_n56(value: UsersListByField): {
    Email: null;
} | {
    Name: null;
} {
    return value == UsersListByField.Email ? {
        Email: null
    } : value == UsersListByField.Name ? {
        Name: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
